#!/bin/bash -e

# riscv64-unknown-elf-gcc -o hello hello.c
# riscv64-unknown-elf-readelf -a hello | less
# riscv64-unknown-elf-objdump -d hello | less
# spike pk hello
# exit

export PATH=~/local/riscvv08/gnu/bin/:$PATH
make
riscv64-unknown-elf-objdump -d bcd2a | less
~/local/riscvv08/spike/bin/spike --isa=RV64gcV \
        ~/local/riscvv08/pk/riscv64-unknown-elf/bin/pk bcd2a

exit
